version: '3'

services:
  mongo-express:
    image: mongo-express
    container_name: diff-tool_mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: bmps
      ME_CONFIG_BASICAUTH_PASSWORD: MyStr0ngP4ssword2019!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MyStr0ngP4ssword2019!
    links:
    - mongo
    networks:
    - mongo-compose-network

  mongo:
    image: mongo
    container_name: diff-tool_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MyStr0ngP4ssword2019!
    ports:
    - "27017:27017"
    volumes:
    - ./mongo-data:/data/db
    networks:
    - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
